// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../library_db.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `play_count_metadata_key`

Future<void> incrementPlayCount({
  required String indexPath,
  required String path,
}) => RustLib.instance.api.crateApiLibraryDbPlayCountsIncrementPlayCount(
  indexPath: indexPath,
  path: path,
);

Future<List<PlayCountEntry>> getTopPlayed({
  required String indexPath,
  required int limit,
}) => RustLib.instance.api.crateApiLibraryDbPlayCountsGetTopPlayed(
  indexPath: indexPath,
  limit: limit,
);

Future<PlatformInt64> getPlayCount({
  required String indexPath,
  required String path,
}) => RustLib.instance.api.crateApiLibraryDbPlayCountsGetPlayCount(
  indexPath: indexPath,
  path: path,
);

Future<List<PlayCountEntry>> exportPlayCounts({required String indexPath}) =>
    RustLib.instance.api.crateApiLibraryDbPlayCountsExportPlayCounts(
      indexPath: indexPath,
    );

/// 按路径或唯一的标题、艺术家、专辑组合写回播放次数；不新建曲库行。
/// `overwrite` 为 false 时取本机与传入值的较大值，为 true 时直接使用传入值。
Future<int> importPlayCounts({
  required String indexPath,
  required List<PlayCountEntry> entries,
  required bool overwrite,
}) => RustLib.instance.api.crateApiLibraryDbPlayCountsImportPlayCounts(
  indexPath: indexPath,
  entries: entries,
  overwrite: overwrite,
);
