// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'tag_reader/extra_metadata.dart';
import 'tag_reader/index_state.dart';
export 'tag_reader/extra_metadata.dart';
export 'tag_reader/index_state.dart';

// These functions are ignored because they are not marked as `pub`: `_get_lyric_from_lofty`, `_get_picture_by_lofty`, `_get_picture_by_windows`, `_picture_cache_key`, `_update_index_below_1_1_0`, `add_missing_audio_files`, `audio_json_is_valid`, `backfill_audio_identity`, `build_alternative_extra_metadata`, `collect_audio_files_by_folder`, `detect_and_encode`, `discover_new_audio_folders`, `drop_invalid_duplicates_by_media_id`, `estimated_bitrate`, `evict_picture_cache_for_path`, `file_name`, `get_embedded_picture_from_path`, `id3_tag_items`, `index_folder_snapshots_unchanged`, `indexed_audio_update_from_parts`, `indexed_audio_update`, `initialize`, `is_image_attachment`, `is_lyric_item_key`, `join_deduped`, `lyrics_text_equiv`, `new_with_path`, `optional_nonempty`, `parse_alternative_number`, `probe_indexed_path`, `push_dsf_item`, `read_alternative_extra_metadata`, `read_asf_extra_metadata`, `read_asf_picture`, `read_audio_paths_parallel`, `read_by_alternative`, `read_by_lofty`, `read_by_win_music_properties`, `read_dff_picture`, `read_dsf_audio_properties`, `read_dsf_extra_metadata`, `read_dsf_picture`, `read_from_folder`, `read_from_path`, `read_id3_from_bytes`, `read_id3_picture`, `read_picture_by_alternative`, `set_audio_json_valid`, `should_emit_index_progress`, `should_scan_indexed_audio_files`, `tag_reader_worker_count_for`, `tag_reader_worker_count`, `take_extra_item`, `to_json_value`, `to_json_value`, `unknown_if_empty`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AudioFolder`, `Audio`, `IndexedAudioUpdate`, `WinRtWorkerGuard`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `drop`, `eq`, `fmt`, `fmt`, `fmt`

/// for Flutter
Future<AudioExtraMetadata> readAudioExtraMetadata({required String path}) =>
    RustLib.instance.api.crateApiTagReaderReadAudioExtraMetadata(path: path);

/// for Flutter
/// 一次调用完成封面读取+颜色提取，避免 image bytes 穿越 FFI 两次
Future<(Uint8List?, Uint32List)> getPictureAndColors({
  required String path,
  required int width,
  required int height,
  required int numColors,
}) => RustLib.instance.api.crateApiTagReaderGetPictureAndColors(
  path: path,
  width: width,
  height: height,
  numColors: numColors,
);

/// for Flutter
/// 如果无法通过 Lofty 获取则通过 Windows 获取
Future<Uint8List?> getPictureFromPath({
  required String path,
  required int width,
  required int height,
}) => RustLib.instance.api.crateApiTagReaderGetPictureFromPath(
  path: path,
  width: width,
  height: height,
);

/// for Flutter
/// 只读取 ID3V2、VorbisComment、Mp4Ilst 存储的内嵌歌词
Future<String?> getLyricFromPath({required String path}) =>
    RustLib.instance.api.crateApiTagReaderGetLyricFromPath(path: path);

/// for Flutter
/// 通用标签写入函数。only_changed=true 时只写非 None 字段
Future<void> writeAudioTags({
  required String path,
  required WriteTagPayload payload,
  required bool onlyChanged,
}) => RustLib.instance.api.crateApiTagReaderWriteAudioTags(
  path: path,
  payload: payload,
  onlyChanged: onlyChanged,
);

/// for Flutter
/// 写入歌词到音频文件标签（ID3/VorbisComment/MP4 等），使用 Lofty 的 `ItemKey::Lyrics` 映射
/// 使用 ParsingMode::Relaxed 兼容更多有问题的标签文件
Future<void> writeLyricToPath({required String path, required String lyric}) =>
    RustLib.instance.api.crateApiTagReaderWriteLyricToPath(
      path: path,
      lyric: lyric,
    );

/// for Flutter
/// 写入内嵌封面图片到音频文件标签。
/// `bytes` 为空时移除封面。图片最长边超过 1600 时等比缩放。
/// 保留原始格式（PNG/JPEG/GIF），无法识别格式时降级为 JPEG。
Future<void> writeAudioCover({
  required String path,
  required List<int> bytes,
}) => RustLib.instance.api.crateApiTagReaderWriteAudioCover(
  path: path,
  bytes: bytes,
);

/// for Flutter
/// 扫描给定路径下所有子文件夹（包括自己）的音乐文件并把索引保存在 index_path/index.json。
Stream<IndexActionState> buildIndexFromFoldersRecursively({
  required List<String> folders,
  required String indexPath,
}) => RustLib.instance.api.crateApiTagReaderBuildIndexFromFoldersRecursively(
  folders: folders,
  indexPath: indexPath,
);

Stream<IndexActionState> updateIndex({
  required String indexPath,
  required bool forceMetadataCheck,
}) => RustLib.instance.api.crateApiTagReaderUpdateIndex(
  indexPath: indexPath,
  forceMetadataCheck: forceMetadataCheck,
);

class WriteTagPayload {
  final String? title;
  final String? artist;
  final String? album;
  final String? albumArtist;
  final String? genre;
  final String? year;
  final String? track;
  final String? trackTotal;
  final String? disc;
  final String? discTotal;
  final String? composer;
  final String? lyricist;
  final String? label;
  final String? comment;
  final String? bpm;
  final String? language;
  final String? copyright;
  final String? license;

  const WriteTagPayload({
    this.title,
    this.artist,
    this.album,
    this.albumArtist,
    this.genre,
    this.year,
    this.track,
    this.trackTotal,
    this.disc,
    this.discTotal,
    this.composer,
    this.lyricist,
    this.label,
    this.comment,
    this.bpm,
    this.language,
    this.copyright,
    this.license,
  });

  @override
  int get hashCode =>
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      albumArtist.hashCode ^
      genre.hashCode ^
      year.hashCode ^
      track.hashCode ^
      trackTotal.hashCode ^
      disc.hashCode ^
      discTotal.hashCode ^
      composer.hashCode ^
      lyricist.hashCode ^
      label.hashCode ^
      comment.hashCode ^
      bpm.hashCode ^
      language.hashCode ^
      copyright.hashCode ^
      license.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WriteTagPayload &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          albumArtist == other.albumArtist &&
          genre == other.genre &&
          year == other.year &&
          track == other.track &&
          trackTotal == other.trackTotal &&
          disc == other.disc &&
          discTotal == other.discTotal &&
          composer == other.composer &&
          lyricist == other.lyricist &&
          label == other.label &&
          comment == other.comment &&
          bpm == other.bpm &&
          language == other.language &&
          copyright == other.copyright &&
          license == other.license;
}
