// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `should_show_recording_date`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`

class AudioExtraItem {
  final String key;
  final String value;

  const AudioExtraItem({required this.key, required this.value});

  @override
  int get hashCode => key.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioExtraItem &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value;
}

class AudioExtraMetadata {
  final String extension_;
  final BigInt fileSize;
  final int? channels;
  final int? bitDepth;
  final List<AudioExtraItem> items;
  final String? replaygainTrackGain;
  final String? replaygainTrackPeak;
  final String? replaygainAlbumGain;
  final String? replaygainAlbumPeak;

  const AudioExtraMetadata({
    required this.extension_,
    required this.fileSize,
    this.channels,
    this.bitDepth,
    required this.items,
    this.replaygainTrackGain,
    this.replaygainTrackPeak,
    this.replaygainAlbumGain,
    this.replaygainAlbumPeak,
  });

  @override
  int get hashCode =>
      extension_.hashCode ^
      fileSize.hashCode ^
      channels.hashCode ^
      bitDepth.hashCode ^
      items.hashCode ^
      replaygainTrackGain.hashCode ^
      replaygainTrackPeak.hashCode ^
      replaygainAlbumGain.hashCode ^
      replaygainAlbumPeak.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioExtraMetadata &&
          runtimeType == other.runtimeType &&
          extension_ == other.extension_ &&
          fileSize == other.fileSize &&
          channels == other.channels &&
          bitDepth == other.bitDepth &&
          items == other.items &&
          replaygainTrackGain == other.replaygainTrackGain &&
          replaygainTrackPeak == other.replaygainTrackPeak &&
          replaygainAlbumGain == other.replaygainAlbumGain &&
          replaygainAlbumPeak == other.replaygainAlbumPeak;
}
