// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class IndexActionState {
  /// completed / total
  final double progress;

  /// describe action state
  final String message;

  const IndexActionState({required this.progress, required this.message});

  @override
  int get hashCode => progress.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IndexActionState &&
          runtimeType == other.runtimeType &&
          progress == other.progress &&
          message == other.message;
}
