// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `collect_symphonia_tags`, `merge_symphonia_field`, `read_symphonia_metadata`, `symphonia_raw_value`, `symphonia_standard_value`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SymphoniaMetadata`

class SymphoniaTagCollection {
  final String? title;
  final String? artist;
  final String? album;
  final String? albumArtist;
  final int? trackNumber;
  final int? discNumber;
  final List<(String, String)> items;
  final Uint8List? picture;

  const SymphoniaTagCollection({
    this.title,
    this.artist,
    this.album,
    this.albumArtist,
    this.trackNumber,
    this.discNumber,
    required this.items,
    this.picture,
  });

  static Future<SymphoniaTagCollection> default_() => RustLib.instance.api
      .crateApiTagReaderSymphoniaSymphoniaTagCollectionDefault();

  @override
  int get hashCode =>
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      albumArtist.hashCode ^
      trackNumber.hashCode ^
      discNumber.hashCode ^
      items.hashCode ^
      picture.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SymphoniaTagCollection &&
          runtimeType == other.runtimeType &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          albumArtist == other.albumArtist &&
          trackNumber == other.trackNumber &&
          discNumber == other.discNumber &&
          items == other.items &&
          picture == other.picture;
}
